//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BlokScriptGrammar.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BlokScript.Parser {
#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="BlokScriptGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IBlokScriptGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] BlokScriptGrammarParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementList([NotNull] BlokScriptGrammarParser.StatementListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] BlokScriptGrammarParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.createDatasourceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateDatasourceStatement([NotNull] BlokScriptGrammarParser.CreateDatasourceStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.deleteDatasourceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteDatasourceStatement([NotNull] BlokScriptGrammarParser.DeleteDatasourceStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.updateDatasourceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdateDatasourceStatement([NotNull] BlokScriptGrammarParser.UpdateDatasourceStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceUpdateList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceUpdateList([NotNull] BlokScriptGrammarParser.DatasourceUpdateListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceUpdate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceUpdate([NotNull] BlokScriptGrammarParser.DatasourceUpdateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.createDatasourceEntryStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateDatasourceEntryStatement([NotNull] BlokScriptGrammarParser.CreateDatasourceEntryStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.deleteDatasourceEntryStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteDatasourceEntryStatement([NotNull] BlokScriptGrammarParser.DeleteDatasourceEntryStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.updateDatasourceEntryStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdateDatasourceEntryStatement([NotNull] BlokScriptGrammarParser.UpdateDatasourceEntryStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntryFullSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntryFullSpec([NotNull] BlokScriptGrammarParser.DatasourceEntryFullSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntryShortSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntryShortSpec([NotNull] BlokScriptGrammarParser.DatasourceEntryShortSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntryIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntryIdentifier([NotNull] BlokScriptGrammarParser.DatasourceEntryIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.updateDatasourceEntriesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdateDatasourceEntriesStatement([NotNull] BlokScriptGrammarParser.UpdateDatasourceEntriesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.deleteDatasourceEntriesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteDatasourceEntriesStatement([NotNull] BlokScriptGrammarParser.DeleteDatasourceEntriesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.copyDatasourceEntriesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopyDatasourceEntriesStatement([NotNull] BlokScriptGrammarParser.CopyDatasourceEntriesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.syncDatasourceEntriesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSyncDatasourceEntriesStatement([NotNull] BlokScriptGrammarParser.SyncDatasourceEntriesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntryCopyOptionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntryCopyOptionList([NotNull] BlokScriptGrammarParser.DatasourceEntryCopyOptionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntryCopyOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntryCopyOption([NotNull] BlokScriptGrammarParser.DatasourceEntryCopyOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntryUpdateList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntryUpdateList([NotNull] BlokScriptGrammarParser.DatasourceEntryUpdateListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntryUpdate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntryUpdate([NotNull] BlokScriptGrammarParser.DatasourceEntryUpdateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntriesSourceLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntriesSourceLocation([NotNull] BlokScriptGrammarParser.DatasourceEntriesSourceLocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.urlSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUrlSpec([NotNull] BlokScriptGrammarParser.UrlSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntriesTargetLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntriesTargetLocation([NotNull] BlokScriptGrammarParser.DatasourceEntriesTargetLocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntryConstraintExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntryConstraintExprList([NotNull] BlokScriptGrammarParser.DatasourceEntryConstraintExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntryConstraintExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntryConstraintExpr([NotNull] BlokScriptGrammarParser.DatasourceEntryConstraintExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntryConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntryConstraint([NotNull] BlokScriptGrammarParser.DatasourceEntryConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.loginStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoginStatement([NotNull] BlokScriptGrammarParser.LoginStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.loginOnlyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoginOnlyStatement([NotNull] BlokScriptGrammarParser.LoginOnlyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.loginWithGlobalUserNameStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoginWithGlobalUserNameStatement([NotNull] BlokScriptGrammarParser.LoginWithGlobalUserNameStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.loginWithGlobalPasswordStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoginWithGlobalPasswordStatement([NotNull] BlokScriptGrammarParser.LoginWithGlobalPasswordStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.loginWithGlobalTokenStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoginWithGlobalTokenStatement([NotNull] BlokScriptGrammarParser.LoginWithGlobalTokenStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.loginWithGlobalUserNameAndPasswordStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoginWithGlobalUserNameAndPasswordStatement([NotNull] BlokScriptGrammarParser.LoginWithGlobalUserNameAndPasswordStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.varStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarStatement([NotNull] BlokScriptGrammarParser.VarStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.spaceVarStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpaceVarStatement([NotNull] BlokScriptGrammarParser.SpaceVarStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.blockVarStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockVarStatement([NotNull] BlokScriptGrammarParser.BlockVarStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.stringVarStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringVarStatement([NotNull] BlokScriptGrammarParser.StringVarStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.regexVarStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegexVarStatement([NotNull] BlokScriptGrammarParser.RegexVarStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.storyVarStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStoryVarStatement([NotNull] BlokScriptGrammarParser.StoryVarStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntryVarStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntryVarStatement([NotNull] BlokScriptGrammarParser.DatasourceEntryVarStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.spaceSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpaceSpec([NotNull] BlokScriptGrammarParser.SpaceSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.shortSpaceSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShortSpaceSpec([NotNull] BlokScriptGrammarParser.ShortSpaceSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.longOrShortSpaceSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLongOrShortSpaceSpec([NotNull] BlokScriptGrammarParser.LongOrShortSpaceSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.blockSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockSpec([NotNull] BlokScriptGrammarParser.BlockSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.storySpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStorySpec([NotNull] BlokScriptGrammarParser.StorySpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceEntrySpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceEntrySpec([NotNull] BlokScriptGrammarParser.DatasourceEntrySpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceSpec([NotNull] BlokScriptGrammarParser.DatasourceSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceShortSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceShortSpec([NotNull] BlokScriptGrammarParser.DatasourceShortSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentStatement([NotNull] BlokScriptGrammarParser.AssignmentStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.spaceAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpaceAssignmentStatement([NotNull] BlokScriptGrammarParser.SpaceAssignmentStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.blockAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockAssignmentStatement([NotNull] BlokScriptGrammarParser.BlockAssignmentStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.stringAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringAssignmentStatement([NotNull] BlokScriptGrammarParser.StringAssignmentStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.copySpacesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopySpacesStatement([NotNull] BlokScriptGrammarParser.CopySpacesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStatement([NotNull] BlokScriptGrammarParser.PrintStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.printSpacesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintSpacesStatement([NotNull] BlokScriptGrammarParser.PrintSpacesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.printVarStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintVarStatement([NotNull] BlokScriptGrammarParser.PrintVarStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.printSpaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintSpaceStatement([NotNull] BlokScriptGrammarParser.PrintSpaceStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.printStringLiteralStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStringLiteralStatement([NotNull] BlokScriptGrammarParser.PrintStringLiteralStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.printSymbolTableStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintSymbolTableStatement([NotNull] BlokScriptGrammarParser.PrintSymbolTableStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.printLocalCacheStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintLocalCacheStatement([NotNull] BlokScriptGrammarParser.PrintLocalCacheStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.realDataLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRealDataLocation([NotNull] BlokScriptGrammarParser.RealDataLocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.spacesOutputLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpacesOutputLocation([NotNull] BlokScriptGrammarParser.SpacesOutputLocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.fileSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFileSpec([NotNull] BlokScriptGrammarParser.FileSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.blockOutputLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockOutputLocation([NotNull] BlokScriptGrammarParser.BlockOutputLocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.blocksOutputLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlocksOutputLocation([NotNull] BlokScriptGrammarParser.BlocksOutputLocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.storyOutputLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStoryOutputLocation([NotNull] BlokScriptGrammarParser.StoryOutputLocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.spaceOutputLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpaceOutputLocation([NotNull] BlokScriptGrammarParser.SpaceOutputLocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.varGetFrom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarGetFrom([NotNull] BlokScriptGrammarParser.VarGetFromContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.createBlockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreateBlockStatement([NotNull] BlokScriptGrammarParser.CreateBlockStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.updateBlocksStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdateBlocksStatement([NotNull] BlokScriptGrammarParser.UpdateBlocksStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.copyBlocksStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopyBlocksStatement([NotNull] BlokScriptGrammarParser.CopyBlocksStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.deleteBlocksStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteBlocksStatement([NotNull] BlokScriptGrammarParser.DeleteBlocksStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.blockConstraintExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockConstraintExprList([NotNull] BlokScriptGrammarParser.BlockConstraintExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.blockConstraintExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockConstraintExpr([NotNull] BlokScriptGrammarParser.BlockConstraintExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.blockConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockConstraint([NotNull] BlokScriptGrammarParser.BlockConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.blockUpdateList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockUpdateList([NotNull] BlokScriptGrammarParser.BlockUpdateListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.blockUpdate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockUpdate([NotNull] BlokScriptGrammarParser.BlockUpdateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.intExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntExprList([NotNull] BlokScriptGrammarParser.IntExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.intExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntExpr([NotNull] BlokScriptGrammarParser.IntExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.verbosityStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVerbosityStatement([NotNull] BlokScriptGrammarParser.VerbosityStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.waitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWaitStatement([NotNull] BlokScriptGrammarParser.WaitStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.compareStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompareStatement([NotNull] BlokScriptGrammarParser.CompareStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.compareSpacesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompareSpacesStatement([NotNull] BlokScriptGrammarParser.CompareSpacesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.compareBlocksStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompareBlocksStatement([NotNull] BlokScriptGrammarParser.CompareBlocksStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.compareAllBlocksStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompareAllBlocksStatement([NotNull] BlokScriptGrammarParser.CompareAllBlocksStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.storiesInputLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStoriesInputLocation([NotNull] BlokScriptGrammarParser.StoriesInputLocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.storiesOutputLocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStoriesOutputLocation([NotNull] BlokScriptGrammarParser.StoriesOutputLocationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.copyStoriesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopyStoriesStatement([NotNull] BlokScriptGrammarParser.CopyStoriesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.publishStoriesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPublishStoriesStatement([NotNull] BlokScriptGrammarParser.PublishStoriesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.unpublishStoriesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnpublishStoriesStatement([NotNull] BlokScriptGrammarParser.UnpublishStoriesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.deleteStoriesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteStoriesStatement([NotNull] BlokScriptGrammarParser.DeleteStoriesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.storyConstraintExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStoryConstraintExprList([NotNull] BlokScriptGrammarParser.StoryConstraintExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.storyConstraintExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStoryConstraintExpr([NotNull] BlokScriptGrammarParser.StoryConstraintExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.storyConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStoryConstraint([NotNull] BlokScriptGrammarParser.StoryConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.regexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegexExpr([NotNull] BlokScriptGrammarParser.RegexExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.regexExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegexExprList([NotNull] BlokScriptGrammarParser.RegexExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.copyDatasourcesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCopyDatasourcesStatement([NotNull] BlokScriptGrammarParser.CopyDatasourcesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.updateDatasourcesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpdateDatasourcesStatement([NotNull] BlokScriptGrammarParser.UpdateDatasourcesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.deleteDatasourcesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteDatasourcesStatement([NotNull] BlokScriptGrammarParser.DeleteDatasourcesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.syncDatasourcesStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSyncDatasourcesStatement([NotNull] BlokScriptGrammarParser.SyncDatasourcesStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceConstraintExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceConstraintExprList([NotNull] BlokScriptGrammarParser.DatasourceConstraintExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceConstraintExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceConstraintExpr([NotNull] BlokScriptGrammarParser.DatasourceConstraintExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.datasourceConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatasourceConstraint([NotNull] BlokScriptGrammarParser.DatasourceConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.stringExprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringExprList([NotNull] BlokScriptGrammarParser.StringExprListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.stringExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringExpr([NotNull] BlokScriptGrammarParser.StringExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BlokScriptGrammarParser.forEachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachStatement([NotNull] BlokScriptGrammarParser.ForEachStatementContext context);
}
} // namespace BlokScript.Parser
